version: '3'
services:
    pgdb:
        image: postgres:9.5
        container_name: odoo-db
        environment:
          POSTGRES_PASSWORD: "${DBPASS:-odoo}"
          POSTGRES_USER: "${DBUSER:-odoo}"
          PGDATA: "${DBDATA:-/var/lib/postgresql/data/pgdata}"
        volumes:
          - "${DBVOL:-odoo_db_data}:${DBDATA:-/var/lib/postgresql/data/pgdata}"
    odoo:
        image: $ODOO_IMAGE:$ODOO_VERSION
        container_name: odoo-app
        external_links:
            - aeroo:aeroo
        depends_on:
            - pgdb
        volumes:
            - "${WEBDATA:-odoo_web_data}:/opt/odoo/data"
            - "${WEBADDONS:-./addons}:/mnt/extra-addons"
        env_file:
            - .env
        #these extra env items are for nginx-proxy automated reverse proxy
        #we need to design an automated hostname/dns subsystem 
        environment:
         PGHOST: pgdb
         VIRTUAL_HOST: "${VHOST:-odoo.local.khem.io}"
         VIRTUAL_PORT: "${VPORT:-8069}"
         LETSENCRYPT_HOST: "${VHOST:-odoo.local.khem.io}"
         LETSENCRYPT_EMAIL: "${EMAIL:-dev@khemlabs.com}"                

#dependency: nginx-proxy must be running before and must create this network
networks:
  default:
    external:
      name: odoo_network

volumes:
    odoo_db_data:
    odoo_web_data:
