version: '3'
services:
    odoo_base:
        image: $ODOO_IMAGE:$ODOO_VERSION
        external_links:
            - aeroo-docs:aeroo
        # podria ir aca pero puede ser mas practico en quien extiende
        volumes:
            - "${WEBDATA:-odoo_web_data}:/opt/odoo/data"
            - "${WEBADDONS:-./addons}:/mnt/extra-addons"
        env_file:
            - .env
volumes:
    odoo_web_data: