version: '3'
services:
    pgdb:
        image: postgres:9.5
        environment:
           POSTGRES_PASSWORD: "${DBPASS:-odoo}"
           POSTGRES_USER: "${DBUSER:-odoo}"
           PGDATA: "${DBDATA:-/var/lib/postgresql/data/pgdata}"
        volumes:
            - "${DBVOL:-odoo_db_data}:${DBDATA:-/var/lib/postgresql/data/pgdata}"
        extends:
            file: odoo-common.yml
            service: odoo_base
        depends_on:
            - pgdb
    odoo_in:
        extends:
            file: odoo-common.yml
            service: odoo_base
        # command: /bin/bash
        depends_on:
            - pgdb
    odoo_prod:
        extends:
            file: odoo-common.yml
            service: odoo_base
        # command: /bin/bash
        restart: always
        depends_on:
            - pgdb
volumes:
    odoo_db_data:
    odoo_web_data:
